# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'getturndata1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib.pyplot as plt 
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas 
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar 
class Ui_Get(object):
    def setupUi(self, Get):
        Get.setObjectName("Get")
        Get.resize(1105, 695)
        self.gridLayout = QtWidgets.QGridLayout(Get)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Get)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        
        self.figure, self.figaxes = plt.subplots()
        # self.figure.subplots_adjust(left=0.01,top=0.99, right=0.98, bottom=0.01)
        self.canvas = FigureCanvas(self.figure)
        self.toolbar = NavigationToolbar(self.canvas, self.widget)
        self.toolbar.setMinimumSize(QtCore.QSize(0, 41))
        self.toolbar.setMaximumSize(QtCore.QSize(16777215, 41))

        self.gridLayout_3.addWidget(self.toolbar, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.canvas, 1, 0, 1, 1)

        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setMinimumSize(QtCore.QSize(601, 0))
        self.frame.setMaximumSize(QtCore.QSize(601, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.saveBtn = QtWidgets.QPushButton(self.frame)
        self.saveBtn.setGeometry(QtCore.QRect(330, 640, 94, 27))
        self.saveBtn.setObjectName("saveBtn")
        self.openBtn = QtWidgets.QPushButton(self.frame)
        self.openBtn.setGeometry(QtCore.QRect(330, 540, 94, 27))
        self.openBtn.setObjectName("openBtn")
        self.closeBtn = QtWidgets.QPushButton(self.frame)
        self.closeBtn.setGeometry(QtCore.QRect(330, 570, 94, 27))
        self.closeBtn.setObjectName("closeBtn")
        self.widget1 = QtWidgets.QWidget(self.frame)
        self.widget1.setGeometry(QtCore.QRect(10, 540, 301, 131))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_31 = QtWidgets.QLabel(self.widget1)
        self.label_31.setMinimumSize(QtCore.QSize(72, 27))
        self.label_31.setMaximumSize(QtCore.QSize(72, 27))
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_6.addWidget(self.label_31)
        self.name_lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.name_lineEdit.setMinimumSize(QtCore.QSize(221, 27))
        self.name_lineEdit.setMaximumSize(QtCore.QSize(221, 27))
        self.name_lineEdit.setText("")
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.horizontalLayout_6.addWidget(self.name_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_32 = QtWidgets.QLabel(self.widget1)
        self.label_32.setMinimumSize(QtCore.QSize(72, 27))
        self.label_32.setMaximumSize(QtCore.QSize(72, 27))
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_7.addWidget(self.label_32)
        self.id_lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.id_lineEdit.setMinimumSize(QtCore.QSize(221, 27))
        self.id_lineEdit.setMaximumSize(QtCore.QSize(221, 27))
        self.id_lineEdit.setText("")
        self.id_lineEdit.setObjectName("id_lineEdit")
        self.horizontalLayout_7.addWidget(self.id_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_33 = QtWidgets.QLabel(self.widget1)
        self.label_33.setMinimumSize(QtCore.QSize(72, 27))
        self.label_33.setMaximumSize(QtCore.QSize(72, 27))
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_8.addWidget(self.label_33)
        self.tel_lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.tel_lineEdit.setMinimumSize(QtCore.QSize(221, 27))
        self.tel_lineEdit.setMaximumSize(QtCore.QSize(221, 27))
        self.tel_lineEdit.setText("")
        self.tel_lineEdit.setObjectName("tel_lineEdit")
        self.horizontalLayout_8.addWidget(self.tel_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_34 = QtWidgets.QLabel(self.widget1)
        self.label_34.setMinimumSize(QtCore.QSize(72, 27))
        self.label_34.setMaximumSize(QtCore.QSize(72, 27))
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_9.addWidget(self.label_34)
        self.email_lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.email_lineEdit.setMinimumSize(QtCore.QSize(221, 27))
        self.email_lineEdit.setMaximumSize(QtCore.QSize(221, 27))
        self.email_lineEdit.setText("")
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.horizontalLayout_9.addWidget(self.email_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.widget2 = QtWidgets.QWidget(self.frame)
        self.widget2.setGeometry(QtCore.QRect(10, 10, 583, 521))
        self.widget2.setObjectName("widget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.z1 = QtWidgets.QPushButton(self.widget2)
        self.z1.setMinimumSize(QtCore.QSize(101, 101))
        self.z1.setMaximumSize(QtCore.QSize(101, 101))
        self.z1.setText("")
        self.z1.setObjectName("z1")
        self.horizontalLayout.addWidget(self.z1)
        self.z2 = QtWidgets.QPushButton(self.widget2)
        self.z2.setMinimumSize(QtCore.QSize(101, 101))
        self.z2.setMaximumSize(QtCore.QSize(101, 101))
        self.z2.setText("")
        self.z2.setObjectName("z2")
        self.horizontalLayout.addWidget(self.z2)
        self.z3 = QtWidgets.QPushButton(self.widget2)
        self.z3.setMinimumSize(QtCore.QSize(101, 101))
        self.z3.setMaximumSize(QtCore.QSize(101, 101))
        self.z3.setText("")
        self.z3.setObjectName("z3")
        self.horizontalLayout.addWidget(self.z3)
        self.z4 = QtWidgets.QPushButton(self.widget2)
        self.z4.setMinimumSize(QtCore.QSize(101, 101))
        self.z4.setMaximumSize(QtCore.QSize(101, 101))
        self.z4.setText("")
        self.z4.setObjectName("z4")
        self.horizontalLayout.addWidget(self.z4)
        self.z5 = QtWidgets.QPushButton(self.widget2)
        self.z5.setMinimumSize(QtCore.QSize(101, 101))
        self.z5.setMaximumSize(QtCore.QSize(101, 101))
        self.z5.setText("")
        self.z5.setObjectName("z5")
        self.horizontalLayout.addWidget(self.z5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.s1 = QtWidgets.QPushButton(self.widget2)
        self.s1.setMinimumSize(QtCore.QSize(101, 101))
        self.s1.setMaximumSize(QtCore.QSize(101, 101))
        self.s1.setText("")
        self.s1.setObjectName("s1")
        self.horizontalLayout_2.addWidget(self.s1)
        self.s2 = QtWidgets.QPushButton(self.widget2)
        self.s2.setMinimumSize(QtCore.QSize(101, 101))
        self.s2.setMaximumSize(QtCore.QSize(101, 101))
        self.s2.setText("")
        self.s2.setObjectName("s2")
        self.horizontalLayout_2.addWidget(self.s2)
        self.s3 = QtWidgets.QPushButton(self.widget2)
        self.s3.setMinimumSize(QtCore.QSize(101, 101))
        self.s3.setMaximumSize(QtCore.QSize(101, 101))
        self.s3.setText("")
        self.s3.setObjectName("s3")
        self.horizontalLayout_2.addWidget(self.s3)
        self.s4 = QtWidgets.QPushButton(self.widget2)
        self.s4.setMinimumSize(QtCore.QSize(101, 101))
        self.s4.setMaximumSize(QtCore.QSize(101, 101))
        self.s4.setText("")
        self.s4.setObjectName("s4")
        self.horizontalLayout_2.addWidget(self.s4)
        self.s5 = QtWidgets.QPushButton(self.widget2)
        self.s5.setMinimumSize(QtCore.QSize(101, 101))
        self.s5.setMaximumSize(QtCore.QSize(101, 101))
        self.s5.setText("")
        self.s5.setObjectName("s5")
        self.horizontalLayout_2.addWidget(self.s5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.x1 = QtWidgets.QPushButton(self.widget2)
        self.x1.setMinimumSize(QtCore.QSize(101, 101))
        self.x1.setMaximumSize(QtCore.QSize(101, 101))
        self.x1.setText("")
        self.x1.setObjectName("x1")
        self.horizontalLayout_3.addWidget(self.x1)
        self.x2 = QtWidgets.QPushButton(self.widget2)
        self.x2.setMinimumSize(QtCore.QSize(101, 101))
        self.x2.setMaximumSize(QtCore.QSize(101, 101))
        self.x2.setText("")
        self.x2.setObjectName("x2")
        self.horizontalLayout_3.addWidget(self.x2)
        self.x3 = QtWidgets.QPushButton(self.widget2)
        self.x3.setMinimumSize(QtCore.QSize(101, 101))
        self.x3.setMaximumSize(QtCore.QSize(101, 101))
        self.x3.setText("")
        self.x3.setObjectName("x3")
        self.horizontalLayout_3.addWidget(self.x3)
        self.x4 = QtWidgets.QPushButton(self.widget2)
        self.x4.setMinimumSize(QtCore.QSize(101, 101))
        self.x4.setMaximumSize(QtCore.QSize(101, 101))
        self.x4.setText("")
        self.x4.setObjectName("x4")
        self.horizontalLayout_3.addWidget(self.x4)
        self.x5 = QtWidgets.QPushButton(self.widget2)
        self.x5.setMinimumSize(QtCore.QSize(101, 101))
        self.x5.setMaximumSize(QtCore.QSize(101, 101))
        self.x5.setText("")
        self.x5.setObjectName("x5")
        self.horizontalLayout_3.addWidget(self.x5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.yc1 = QtWidgets.QPushButton(self.widget2)
        self.yc1.setMinimumSize(QtCore.QSize(101, 101))
        self.yc1.setMaximumSize(QtCore.QSize(101, 101))
        self.yc1.setText("")
        self.yc1.setObjectName("yc1")
        self.horizontalLayout_4.addWidget(self.yc1)
        self.yc2 = QtWidgets.QPushButton(self.widget2)
        self.yc2.setMinimumSize(QtCore.QSize(101, 101))
        self.yc2.setMaximumSize(QtCore.QSize(101, 101))
        self.yc2.setText("")
        self.yc2.setObjectName("yc2")
        self.horizontalLayout_4.addWidget(self.yc2)
        self.yc3 = QtWidgets.QPushButton(self.widget2)
        self.yc3.setMinimumSize(QtCore.QSize(101, 101))
        self.yc3.setMaximumSize(QtCore.QSize(101, 101))
        self.yc3.setText("")
        self.yc3.setObjectName("yc3")
        self.horizontalLayout_4.addWidget(self.yc3)
        self.yc4 = QtWidgets.QPushButton(self.widget2)
        self.yc4.setMinimumSize(QtCore.QSize(101, 101))
        self.yc4.setMaximumSize(QtCore.QSize(101, 101))
        self.yc4.setText("")
        self.yc4.setObjectName("yc4")
        self.horizontalLayout_4.addWidget(self.yc4)
        self.yc5 = QtWidgets.QPushButton(self.widget2)
        self.yc5.setMinimumSize(QtCore.QSize(101, 101))
        self.yc5.setMaximumSize(QtCore.QSize(101, 101))
        self.yc5.setText("")
        self.yc5.setObjectName("yc5")
        self.horizontalLayout_4.addWidget(self.yc5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.zc1 = QtWidgets.QPushButton(self.widget2)
        self.zc1.setMinimumSize(QtCore.QSize(101, 101))
        self.zc1.setMaximumSize(QtCore.QSize(101, 101))
        self.zc1.setText("")
        self.zc1.setObjectName("zc1")
        self.horizontalLayout_5.addWidget(self.zc1)
        self.zc2 = QtWidgets.QPushButton(self.widget2)
        self.zc2.setMinimumSize(QtCore.QSize(101, 101))
        self.zc2.setMaximumSize(QtCore.QSize(101, 101))
        self.zc2.setText("")
        self.zc2.setObjectName("zc2")
        self.horizontalLayout_5.addWidget(self.zc2)
        self.zc3 = QtWidgets.QPushButton(self.widget2)
        self.zc3.setMinimumSize(QtCore.QSize(101, 101))
        self.zc3.setMaximumSize(QtCore.QSize(101, 101))
        self.zc3.setText("")
        self.zc3.setObjectName("zc3")
        self.horizontalLayout_5.addWidget(self.zc3)
        self.zc4 = QtWidgets.QPushButton(self.widget2)
        self.zc4.setMinimumSize(QtCore.QSize(101, 101))
        self.zc4.setMaximumSize(QtCore.QSize(101, 101))
        self.zc4.setText("")
        self.zc4.setObjectName("zc4")
        self.horizontalLayout_5.addWidget(self.zc4)
        self.zc5 = QtWidgets.QPushButton(self.widget2)
        self.zc5.setMinimumSize(QtCore.QSize(101, 101))
        self.zc5.setMaximumSize(QtCore.QSize(101, 101))
        self.zc5.setText("")
        self.zc5.setObjectName("zc5")
        self.horizontalLayout_5.addWidget(self.zc5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.widget3 = QtWidgets.QWidget(self.frame)
        self.widget3.setGeometry(QtCore.QRect(430, 540, 96, 128))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.gridLayout_2.addWidget(self.frame, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Get)
        QtCore.QMetaObject.connectSlotsByName(Get)

    def retranslateUi(self, Get):
        _translate = QtCore.QCoreApplication.translate
        Get.setWindowTitle(_translate("Get", "Form"))
        self.saveBtn.setText(_translate("Get", "保存信息"))
        self.openBtn.setText(_translate("Get", "打开摄像头"))
        self.closeBtn.setText(_translate("Get", "关闭摄像头"))
        self.label_31.setText(_translate("Get", "<html><head/><body><p align=\"right\">姓名：</p></body></html>"))
        self.label_32.setText(_translate("Get", "<html><head/><body><p align=\"right\">身份证：</p></body></html>"))
        self.label_33.setText(_translate("Get", "<html><head/><body><p align=\"right\">电话：</p></body></html>"))
        self.label_34.setText(_translate("Get", "<html><head/><body><p align=\"right\">邮箱：</p></body></html>"))
        self.label.setText(_translate("Get", "<html><head/><body><p align=\"right\">正脸：</p></body></html>"))
        self.label_2.setText(_translate("Get", "<html><head/><body><p align=\"right\">上脸：</p></body></html>"))
        self.label_3.setText(_translate("Get", "<html><head/><body><p align=\"right\">下脸：</p></body></html>"))
        self.label_4.setText(_translate("Get", "<html><head/><body><p align=\"right\">右侧脸：</p></body></html>"))
        self.label_5.setText(_translate("Get", "<html><head/><body><p align=\"right\">左侧脸：</p></body></html>"))
        self.pushButton_4.setText(_translate("Get", "PushButton"))
        self.pushButton_5.setText(_translate("Get", "PushButton"))
        self.pushButton_6.setText(_translate("Get", "PushButton"))
        self.pushButton_7.setText(_translate("Get", "PushButton"))

