# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imagerecognition.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='imagerecognition.proto',
  package='recognition',
  syntax='proto3',
  serialized_pb=_b('\n\x16imagerecognition.proto\x12\x0brecognition\"=\n\nImgRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x10\n\x08\x66iletype\x18\x02 \x01(\t\x12\x0b\n\x03img\x18\x03 \x01(\x0c\"h\n\x0ePositiveIDInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03sex\x18\x02 \x01(\t\x12\x0e\n\x06nation\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x05 \x01(\t\x12\x10\n\x08IDnumber\x18\x06 \x01(\t\"<\n\rReverseIDInfo\x12\x14\n\x0corganization\x18\x01 \x01(\t\x12\x15\n\reffectivedate\x18\x02 \x01(\t2\xa0\x01\n\x10ImageRecognition\x12\x46\n\nPositiveID\x12\x17.recognition.ImgRequest\x1a\x1b.recognition.PositiveIDInfo\"\x00(\x01\x12\x44\n\tReverseID\x12\x17.recognition.ImgRequest\x1a\x1a.recognition.ReverseIDInfo\"\x00(\x01\x42\x12\n\x10io.grpc.examplesb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IMGREQUEST = _descriptor.Descriptor(
  name='ImgRequest',
  full_name='recognition.ImgRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='recognition.ImgRequest.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filetype', full_name='recognition.ImgRequest.filetype', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='img', full_name='recognition.ImgRequest.img', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=100,
)


_POSITIVEIDINFO = _descriptor.Descriptor(
  name='PositiveIDInfo',
  full_name='recognition.PositiveIDInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='recognition.PositiveIDInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sex', full_name='recognition.PositiveIDInfo.sex', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nation', full_name='recognition.PositiveIDInfo.nation', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='age', full_name='recognition.PositiveIDInfo.age', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='addr', full_name='recognition.PositiveIDInfo.addr', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IDnumber', full_name='recognition.PositiveIDInfo.IDnumber', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=206,
)


_REVERSEIDINFO = _descriptor.Descriptor(
  name='ReverseIDInfo',
  full_name='recognition.ReverseIDInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='organization', full_name='recognition.ReverseIDInfo.organization', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='effectivedate', full_name='recognition.ReverseIDInfo.effectivedate', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=268,
)

DESCRIPTOR.message_types_by_name['ImgRequest'] = _IMGREQUEST
DESCRIPTOR.message_types_by_name['PositiveIDInfo'] = _POSITIVEIDINFO
DESCRIPTOR.message_types_by_name['ReverseIDInfo'] = _REVERSEIDINFO

ImgRequest = _reflection.GeneratedProtocolMessageType('ImgRequest', (_message.Message,), dict(
  DESCRIPTOR = _IMGREQUEST,
  __module__ = 'imagerecognition_pb2'
  # @@protoc_insertion_point(class_scope:recognition.ImgRequest)
  ))
_sym_db.RegisterMessage(ImgRequest)

PositiveIDInfo = _reflection.GeneratedProtocolMessageType('PositiveIDInfo', (_message.Message,), dict(
  DESCRIPTOR = _POSITIVEIDINFO,
  __module__ = 'imagerecognition_pb2'
  # @@protoc_insertion_point(class_scope:recognition.PositiveIDInfo)
  ))
_sym_db.RegisterMessage(PositiveIDInfo)

ReverseIDInfo = _reflection.GeneratedProtocolMessageType('ReverseIDInfo', (_message.Message,), dict(
  DESCRIPTOR = _REVERSEIDINFO,
  __module__ = 'imagerecognition_pb2'
  # @@protoc_insertion_point(class_scope:recognition.ReverseIDInfo)
  ))
_sym_db.RegisterMessage(ReverseIDInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\020io.grpc.examples'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class ImageRecognitionStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.PositiveID = channel.stream_unary(
          '/recognition.ImageRecognition/PositiveID',
          request_serializer=ImgRequest.SerializeToString,
          response_deserializer=PositiveIDInfo.FromString,
          )
      self.ReverseID = channel.stream_unary(
          '/recognition.ImageRecognition/ReverseID',
          request_serializer=ImgRequest.SerializeToString,
          response_deserializer=ReverseIDInfo.FromString,
          )


  class ImageRecognitionServicer(object):

    def PositiveID(self, request_iterator, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def ReverseID(self, request_iterator, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_ImageRecognitionServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'PositiveID': grpc.stream_unary_rpc_method_handler(
            servicer.PositiveID,
            request_deserializer=ImgRequest.FromString,
            response_serializer=PositiveIDInfo.SerializeToString,
        ),
        'ReverseID': grpc.stream_unary_rpc_method_handler(
            servicer.ReverseID,
            request_deserializer=ImgRequest.FromString,
            response_serializer=ReverseIDInfo.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'recognition.ImageRecognition', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaImageRecognitionServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def PositiveID(self, request_iterator, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def ReverseID(self, request_iterator, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaImageRecognitionStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def PositiveID(self, request_iterator, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    PositiveID.future = None
    def ReverseID(self, request_iterator, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    ReverseID.future = None


  def beta_create_ImageRecognition_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('recognition.ImageRecognition', 'PositiveID'): ImgRequest.FromString,
      ('recognition.ImageRecognition', 'ReverseID'): ImgRequest.FromString,
    }
    response_serializers = {
      ('recognition.ImageRecognition', 'PositiveID'): PositiveIDInfo.SerializeToString,
      ('recognition.ImageRecognition', 'ReverseID'): ReverseIDInfo.SerializeToString,
    }
    method_implementations = {
      ('recognition.ImageRecognition', 'PositiveID'): face_utilities.stream_unary_inline(servicer.PositiveID),
      ('recognition.ImageRecognition', 'ReverseID'): face_utilities.stream_unary_inline(servicer.ReverseID),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_ImageRecognition_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('recognition.ImageRecognition', 'PositiveID'): ImgRequest.SerializeToString,
      ('recognition.ImageRecognition', 'ReverseID'): ImgRequest.SerializeToString,
    }
    response_deserializers = {
      ('recognition.ImageRecognition', 'PositiveID'): PositiveIDInfo.FromString,
      ('recognition.ImageRecognition', 'ReverseID'): ReverseIDInfo.FromString,
    }
    cardinalities = {
      'PositiveID': cardinality.Cardinality.STREAM_UNARY,
      'ReverseID': cardinality.Cardinality.STREAM_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'recognition.ImageRecognition', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
