# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'usb1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib.pyplot as plt 
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas 
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar 
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1036, 609)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.pic_figure, self.pic_figaxes = plt.subplots()
        # self.pic_figure.subplots_adjust(left=0.01,top=0.99, right=0.98, bottom=0.01)
        self.pic_canvas = FigureCanvas(self.pic_figure)
        self.pic_toolbar = NavigationToolbar(self.pic_canvas, self.frame_2)
        self.pic_toolbar.setMinimumSize(QtCore.QSize(0, 41))
        self.pic_toolbar.setMaximumSize(QtCore.QSize(16777215, 41))

        self.gridLayout_2.addWidget(self.pic_toolbar, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.pic_canvas, 1, 0, 1, 1)

        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(431, 0))
        self.frame.setMaximumSize(QtCore.QSize(431, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 431, 321))
        self.frame_3.setMinimumSize(QtCore.QSize(431, 321))
        self.frame_3.setMaximumSize(QtCore.QSize(431, 321))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")

        self.video_figure, self.video_figaxes = plt.subplots()
        self.video_figure.subplots_adjust(left=0.01,top=0.99, right=0.98, bottom=0.01)
        self.video_canvas = FigureCanvas(self.video_figure)

        # self.widget_3 = QtWidgets.QWidget(self.frame_3)
        # self.widget_3.setObjectName("widget_3")
        self.gridLayout_3.addWidget(self.video_canvas, 0, 0, 1, 1)
        
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(10, 370, 411, 141))
        self.groupBox.setObjectName("groupBox")
        self.widget1 = QtWidgets.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(210, 30, 191, 104))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setMinimumSize(QtCore.QSize(64, 27))
        self.label_5.setMaximumSize(QtCore.QSize(64, 27))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.widget1)
        self.doubleSpinBox_2.setMinimumSize(QtCore.QSize(109, 27))
        self.doubleSpinBox_2.setMaximumSize(QtCore.QSize(109, 27))
        self.doubleSpinBox_2.setMaximum(10000000.0)
        self.doubleSpinBox_2.setSingleStep(0.1)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.widget1)
        self.label_6.setMinimumSize(QtCore.QSize(64, 27))
        self.label_6.setMaximumSize(QtCore.QSize(64, 27))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.widget1)
        self.doubleSpinBox.setMinimumSize(QtCore.QSize(109, 27))
        self.doubleSpinBox.setMaximumSize(QtCore.QSize(109, 27))
        self.doubleSpinBox.setMaximum(10000000.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.widget1)
        self.label_7.setMinimumSize(QtCore.QSize(64, 27))
        self.label_7.setMaximumSize(QtCore.QSize(64, 27))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.widget1)
        self.doubleSpinBox_5.setMinimumSize(QtCore.QSize(109, 27))
        self.doubleSpinBox_5.setMaximumSize(QtCore.QSize(109, 27))
        self.doubleSpinBox_5.setMaximum(10000000.0)
        self.doubleSpinBox_5.setSingleStep(0.1)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.widget2 = QtWidgets.QWidget(self.groupBox)
        self.widget2.setGeometry(QtCore.QRect(10, 30, 183, 103))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.widget2)
        self.label_2.setMinimumSize(QtCore.QSize(64, 27))
        self.label_2.setMaximumSize(QtCore.QSize(64, 27))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.widget2)
        self.comboBox.setMinimumSize(QtCore.QSize(109, 27))
        self.comboBox.setMaximumSize(QtCore.QSize(109, 27))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.widget2)
        self.label_8.setMinimumSize(QtCore.QSize(64, 27))
        self.label_8.setMaximumSize(QtCore.QSize(64, 27))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.widget2)
        self.doubleSpinBox_3.setMinimumSize(QtCore.QSize(109, 27))
        self.doubleSpinBox_3.setMaximumSize(QtCore.QSize(109, 27))
        self.doubleSpinBox_3.setMaximum(10000000.0)
        self.doubleSpinBox_3.setSingleStep(0.1)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.widget2)
        self.label_9.setMinimumSize(QtCore.QSize(64, 27))
        self.label_9.setMaximumSize(QtCore.QSize(64, 27))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.widget2)
        self.doubleSpinBox_4.setMinimumSize(QtCore.QSize(109, 27))
        self.doubleSpinBox_4.setMaximumSize(QtCore.QSize(109, 27))
        self.doubleSpinBox_4.setMaximum(10000000.0)
        self.doubleSpinBox_4.setSingleStep(0.1)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.widget3 = QtWidgets.QWidget(self.frame)
        self.widget3.setGeometry(QtCore.QRect(280, 330, 141, 31))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.widget3)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget3)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_3.addWidget(self.checkBox_2)
        self.widget4 = QtWidgets.QWidget(self.frame)
        self.widget4.setGeometry(QtCore.QRect(10, 520, 371, 30))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget4)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.widget4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.spinBox = QtWidgets.QSpinBox(self.widget4)
        self.spinBox.setMinimumSize(QtCore.QSize(92, 28))
        self.spinBox.setMaximumSize(QtCore.QSize(92, 28))
        self.spinBox.setMaximum(1000000000)
        self.spinBox.setProperty("value", 600)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.label_4 = QtWidgets.QLabel(self.widget4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget4)
        self.spinBox_2.setMinimumSize(QtCore.QSize(92, 28))
        self.spinBox_2.setMaximumSize(QtCore.QSize(92, 28))
        self.spinBox_2.setMaximum(100000000)
        self.spinBox_2.setProperty("value", 400)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout.addWidget(self.spinBox_2)
        self.widget5 = QtWidgets.QWidget(self.frame)
        self.widget5.setGeometry(QtCore.QRect(10, 330, 261, 31))
        self.widget5.setObjectName("widget5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget5)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget5)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.widget5)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.widget6 = QtWidgets.QWidget(self.frame)
        self.widget6.setGeometry(QtCore.QRect(10, 560, 151, 31))
        self.widget6.setObjectName("widget6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget6)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget6)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "摄像头参数调整"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"right\">亮度：</p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"right\">对比度：</p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p align=\"right\">饱和度：</p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"right\">分辨率：</p></body></html>"))
        self.comboBox.setItemText(0, _translate("Form", "1920*1080"))
        self.comboBox.setItemText(1, _translate("Form", "1600*900"))
        self.comboBox.setItemText(2, _translate("Form", "1280*720"))
        self.comboBox.setItemText(3, _translate("Form", "800*600"))
        self.comboBox.setItemText(4, _translate("Form", "640*480"))
        self.comboBox.setItemText(5, _translate("Form", "600*400"))
        self.comboBox.setItemText(6, _translate("Form", "320*240"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p align=\"right\">色调：</p></body></html>"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p align=\"right\">曝光：</p></body></html>"))
        self.checkBox.setText(_translate("Form", "人脸"))
        self.checkBox_2.setText(_translate("Form", "身份证"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"right\">图像大小(像素)：</p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">宽</p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\">高</p></body></html>"))
        self.pushButton_2.setText(_translate("Form", "打开摄像头"))
        self.pushButton_3.setText(_translate("Form", "打开本地件"))
        self.pushButton.setText(_translate("Form", "抓拍"))
        self.pushButton_5.setText(_translate("Form", "预览"))
        self.pushButton_4.setText(_translate("Form", "保存"))

